from ProfileSet import Document
from FeatureSet import FeatureSet
class PreProcessor:

    settings = dict()
    def toDocStr(self, file, filters):
        """Returns docstring after desired preprocessing filters are applied in order"""
        contents=open(file, 'r').read()
        for filter in filters:
            contents = filter.apply(contents)
            
        features = FeatureSet(contents)

        return contents

    def tokenize(self, docStr, tokenizer):
        """Returns a list of tokens generated by the chosen tokenizer"""

class Filter:
    def apply(self, docStr):
        pass

    